### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by GitSRealpe** [GitSRealpe/abb_irb140_ros_sim#6]
Somethings are needed to do:
- [x] Change the joint_commander msg type from `Num`.msg to `Joints.msg`.
- [ ] Change the joint_commander topic from `cmd_vel` to `cmd_joints`.
- [ ] edit wiki with new changes:
[ ] workspace now under catkin tools, so build command is with catkin build
- [x] Add bin and shelf collision models to moveit scene
- [ ] Update the wiki according to the 2022 changes

**Comment by GitSRealpe** [comment]
- [ ] edit wiki with new changes:
[ ] workspace now under catkin tools, so build command is with catkin build
